project:
  type: website
  output-dir: docs

website:
  title: "BADT26"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/course_intro.qmd
        text: Course introduction
      - href: pages/Bayesian_inference_subjective_probability.qmd
        text: Bayesian inference subjective probability
      - href: pages/exercise_1.qmd
        text: Exercise 1
      - href: pages/exercise_2.qmd
        text: Exercise 2
      - href: pages/MCMC.qmd
        text: Markov chain monte carlo
      - href: pages/exercise_3.qmd
        text: Exercise 3
      - href: pages/PP.qmd
        text: Predictive performance

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



