project:
  type: website
  output-dir: docs

website:
  title: "BADT26"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/course_intro.qmd
        text: Course introduction
      - href: pages/Bayesian_inference_subjective_probability.qmd
        text: Bayesian inference
      - href: pages/exercise_1.qmd
        text: E1
      - href: pages/conjugate_models.qmd
        text: Conjugate models
      - href: pages/exercise_2.qmd
        text: E2
      - href: pages/MCMC.qmd
        text: MCMC
      - href: pages/exercise_3.qmd
        text: E3
      - href: pages/PP.qmd
        text: Predictive performance
      - href: pages/exercise_4.qmd
        text: E4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



